spring.application.name=taskmanager

#1.Configuración: Conexión a Base de Datos(JDBC)
spring.datasource.url=jdbc:mariadb://localhost:3306/taskmanager
spring.datasource.username=developer
spring.datasource.password=password_secreto
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#3. Propiedades de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
